### ISSUE TITLE
External Sharing Disabled Scenarios

### ISSUE THREAD

**Issue by NavaneethaDev** [bschlintz/spfx-external-sharing-banner#1]
What will happen if external sharing is disabled on the site collection level? Will your solution still work? We shouldnt display any banner when the external sharing is disabled right? Thanks

**Comment by bschlintz** [comment]
The banner would not render if external sharing is disabled at the site collection because no external content would be on the site. The solution uses the SharePoint Search service to discover externally viewable content that the current user has access to read when determining whether the banner should show. 

If the `scope` is set to `site`, then the banner will be displayed if there is any external content in the site collection. Similarly, if the `scope` is set to `web`, the banner will show if there is any external content on just the current web ignoring any subsites. In all cases, the banner will only show if the current user can see the external content.
